### ISSUE TITLE
Unable to generate payload exe file

### ISSUE THREAD

**Issue by whlweb** [nccgroup/Winpayloads#40] opened 2017-08-18 00:51 UTC
Hi I'm having trouble generating the exe file, although the log said it was generated, but there was actually nothing in the folder.

Main Menu > 2

[*] Press Enter For Default Port($<2>4444$<2>)
[*] Port> 5901

[*] Press Enter To Get Local Ip Automatically($<2>192.168.0.19$<2>)
[*] IP> 189.172.81.241
$<2>[*] IP SET AS 189.172.81.241
[*] PORT SET AS 5901
$<2>
$<2>[*] Try UAC Bypass(Only Works For Local Admin Account)?$<2> y/[n]:$<2>y
$<2>[*] Windows 7 or 10?$<2> 7/[10]:$<2>7
[*] Creating Payload using Pyinstaller...
mv: cannot stat 'dist/payload.exe': No such file or directory
$<2>
[*] Payload.exe Has Been Generated And Is Located Here: $<2>/root/winpayloads/Windows_Meterpreter_Reverse_Shell.exe$<2>
rm: cannot remove 'dist': No such file or directory
rm: cannot remove 'build': No such file or directory
rm: cannot remove '*.spec': No such file or directory

**Comment by back2Lobby** [comment] 2017-08-18 10:03
I am facing same problem!

**Comment by Charliedean** [comment] 2017-08-18 10:22
Hi can you post the output of payload generation when running winpayloads with the -debug flag?
`./Winpayloads.py -debug`

**Comment by Charliedean** [comment] 2017-08-18 10:25
Please re run the setup and try again
https://github.com/nccgroup/Winpayloads/commit/3b7b206b17678a926fc932203adb031c994b6b9d

**Comment by protected-void** [comment] 2017-08-18 10:26
@Charliedean beat me to the solution, darn.

Semi-duplicate of #38

**Closed as completed** 2017-09-04 07:29 UTC
